<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('CityIT')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/admin.css'))
        ->prependStylesheet($this->basePath('css/jquery.layout.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/admin/admin.js'))
        ->prependFile($this->basePath('js/admin/jquery.ui.all.js'))
        ->prependFile($this->basePath('js/admin/jquery.layout.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>

    <script>
        $(document).ready(function () {
            $('#container').layout();
        });
    </script>
</head>
<body>
<div id="container">
    <div class="pane ui-layout-center">
        <?= $this->content ?>
    </div>
    <div class="pane ui-layout-north header">
        <div>
            <table cellspacing="0" cellpadding="0">
                <tr>
                    <td class="col-1"><?= date('l') ?> <strong><?= date('d F Y') ?></strong> <?= date('H:i') ?></td>
                    <td class="col-2"></td>
                    <td class="col-3"><span data-toggle="" data-lng="bg_BG">bg_BG</span> <span data-toggle=""
                                                                                               data-lng="en_GB">en_GB</span>
                    </td>
                </tr>
            </table>
        </div>
    </div>
<!--    <div class="pane ui-layout-south">South</div>-->
<!--    <div class="pane ui-layout-east">East</div>-->
    <div class="pane ui-layout-west">
        <?= $this->navigation('Zend\Navigation\AdminMenu')->menu() ?>
    </div>
</div>

<?= $this->inlineScript() ?>
</body>
</html>
