<h1>Menu</h1>

<style>
    th, td {
        padding: 5px 10px;
    }
</style>

<?php

echo $this->paginationControl($paginator, 'Sliding', 'admin/partials/paginator', ['route' => 'home']);

echo $this->partial('admin/partials/searchForm', [
    'searchList' => $this->searchList,
    'searchForm' => $this->searchForm,
    'languages' => $this->languages,
]);

?>

<form action="" method="POST">
    <?= $listTable->getListTable($this->url('home', ['action' => 'edit'])) ?>
</form>