<h1>Menu</h1>

<style>
    th, td {
        padding: 5px 10px;
    }
</style>

<?php

echo $this->paginationControl($paginator, 'Sliding', 'admin/partials/paginator', ['route' => 'home']);

if (!empty($searchModel)) {
//        $searchForm->prepare();
    echo $this->form()->openTag($searchForm);
    foreach ($searchModel as $key => $item) {
        echo $this->formLabel($searchForm->get($key));
        echo $this->formElement($searchForm->get($key));
    }

    echo $this->formElement($searchForm->get('submit'));
    echo $this->formElement($searchForm->get('clear'));
    echo $this->form()->closeTag();
}
?>

<form action="" method="POST">
    <?= $listTable->getListTable($this->url('home', ['action' => 'edit'])) ?>
</form>