<h1>Menu</h1>

<div class="admin-content-wrap">
    <?php

    echo $this->partial('admin/partials/searchForm', [
        'searchList' => $this->searchList,
        'searchForm' => $this->searchForm,
        'languages' => $this->languages,
    ]);

    ?>

    <form action="" method="POST">
        <?= $this->paginationControl($paginator, 'Sliding', 'admin/partials/paginator', ['route' => $this->routeName, 'ipp'=>$paginator->getItemCountPerPage()]) ?>
        <?= $listTable->getTableHtml() ?>
    </form>

</div>