<?php
$this->headLink()->prependStylesheet($this->basePath('css/bootstrap.css'));
$this->headLink()->prependStylesheet($this->basePath('nestable/nestable.css'));
$this->headScript()->prependFile($this->basePath('js/bootstrap.js'));
$this->headScript()->prependFile($this->basePath('nestable/jquery.nestable.js'));
?>

<div class="row">
    <div class="col-md-8">
        <div class="well">
            <form id="add-menu" action="<?= $this->url('menu', ['action'=>'add']) ?>">
            <p class="lead">

                <button type="button" id="add-child" href="<?= $this->url('menu', ['action' => 'add']) ?>" class="btn btn-default pull-right"><span
                        class="glyphicon glyphicon-plus-sign"></span> Add as child of</button>
                <span class="pull-right" style="padding-left: 15px;">&nbsp;</span>
                <button type="button" id="add-after" href="<?= $this->url('menu', ['action' => 'add']) ?>" class="btn btn-default pull-right"><span
                        class="glyphicon glyphicon-plus-sign"></span> Add after</button>

            Menu:</p>
            </form>
            <div class="dd" id="nestable">
                <?= $menu ?>
            </div>

            <p id="success-indicator" style="display:none; margin-right: 10px;">
                <span class="glyphicon glyphicon-ok"></span> Menu order has been saved
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="well">
            <p>Drag items to move them in a different order</p>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('.dd').nestable({
            dropCallback: function (details) {

                var order = new Array();
                $("li[data-id='" + details.destId + "']").find('ol:first').children().each(function (index, elem) {
                    order[index] = $(elem).attr('data-id');
                });
                if (order.length === 0) {
                    var rootOrder = new Array();
                    $("#nestable > ol > li").each(function (index, elem) {
                        rootOrder[index] = $(elem).attr('data-id');
                    });
                }
                $.post('<?= $this->url('menu', ['action'=>'tree']) ?>',
                    {
                        source: details.sourceId,
                        destination: details.destId,
                        order: JSON.stringify(order),
                        rootOrder: JSON.stringify(rootOrder)
                    },
                    function (data) {
                        // console.log('data '+data);
                    })
                    .done(function () {
                        $("#success-indicator").fadeIn(100).delay(1000).fadeOut();
                    })
                    .fail(function () {
                    })
                    .always(function () {
                    });
            }
        });
    });
    $('.nested-list-content .selected').click(function (e) {
        e.preventDefault();
        $('.nested-list-content.selected').removeClass('selected');
        $(this).parents('.nested-list-content').toggleClass('selected');
    });

    $('#add-after').click(function(e){
        doAction2('#add-menu', 'addAfter', $('.nested-list-content.selected .selected').attr('data-id'));
    });
    $('#add-child').click(function(e){
        doAction2('#add-menu', 'addChild', $('.nested-list-content.selected .selected').attr('data-id'));
    });

</script>