<?php
$this->headLink()->prependStylesheet($this->basePath('css/bootstrap.css'));
$this->headLink()->prependStylesheet($this->basePath('nestable/nestable.css'));
$this->headScript()->prependFile($this->basePath('js/bootstrap.js'));
$this->headScript()->prependFile($this->basePath('nestable/jquery.nestable.js'));
?>

<div class="row">
    <div class="col-md-8">
        <div class="well">
            <p class="lead"><a href="#newModal" class="btn btn-default pull-right" data-toggle="modal"><span
                        class="glyphicon glyphicon-plus-sign"></span> new menu item</a> Menu:</p>

            <div class="dd" id="nestable">
                <?= $menu ?>
            </div>

            <p id="success-indicator" style="display:none; margin-right: 10px;">
                <span class="glyphicon glyphicon-ok"></span> Menu order has been saved
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="well">
            <p>Drag items to move them in a different order</p>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('.dd').nestable({
            dropCallback: function (details) {

                var order = new Array();
                $("li[data-id='" + details.destId + "']").find('ol:first').children().each(function (index, elem) {
                    order[index] = $(elem).attr('data-id');
                });
                if (order.length === 0) {
                    var rootOrder = new Array();
                    $("#nestable > ol > li").each(function (index, elem) {
                        rootOrder[index] = $(elem).attr('data-id');
                    });
                }
                $.post('<?= $this->url('menu', ['action'=>'tree']) ?>',
                    {
                        source: details.sourceId,
                        destination: details.destId,
                        order: JSON.stringify(order),
                        rootOrder: JSON.stringify(rootOrder)
                    },
                    function (data) {
                        // console.log('data '+data);
                    })
                    .done(function () {
                        $("#success-indicator").fadeIn(100).delay(1000).fadeOut();
                    })
                    .fail(function () {
                    })
                    .always(function () {
                    });
            }
        });
    });
</script>