<div class="edit-form">
    <div class="title">Edit</div>
        <?php
        $tr = [];
        $errors = [];
        if (!empty($this->edit)) {
            foreach ($this->edit as $key => $item) {
                $field = '';
                if (is_array($item)) {
                    $field = $key;
                } else {
                    $field = $item;
                }
                $tFields = \Libs\Admin\Helper::transformFiled($field, $this->languages);
                foreach ($tFields as $tField) {
                    $label = $this->formLabel($this->editForm->get($tField));
                    $error = $this->formElementErrors($this->editForm->get($tField));
                    if(!empty($error)) {
                        $errors[] = $label . $this->formElementErrors($this->editForm->get($tField));
                    }
                    $td = [];
                    $td[] = '<td>' . $label . '</td>';
                    $td[] = '<td>' . $this->formElement($this->editForm->get($tField)) . '</td>';
                    $tr[] = implode('', $td);
                }
            }

            if(!empty($errors)) {
                echo '<div class="errors">' . implode('', $errors) . '</div>';
            }
            echo $this->form()->openTag($this->editForm);
            echo '<div class="fields">';
            echo '<table cellpadding="0" cellspacing="0" class="edit-table"><tr>' . implode('</tr><tr>', $tr) . '</tr></table>';
            echo '</div>';
            echo '<div class="footer">';
            echo $this->formElement($this->editForm->get('save'));
            echo '</div>';
            echo $this->form()->closeTag();
        }
        ?>
</div>
