<h1>Menu</h1>

<div class="admin-content-wrap">
    <?php

    echo $this->partial('admin/admin/searchForm', [
        'searchList' => $this->searchList,
        'searchForm' => $this->searchForm,
        'languages' => $this->languages,
    ]);

    ?>

    <form action="" method="POST">
        <div class="list-data-wrap">
            <div class="buttons">
                <ul>
                    <li><a href="<?= $this->url($this->routeName, ['action' => 'add']) ?>" title="Add record"
                           class="add-record">Add record</a></li>
                    <li>
                        <button type="submit" name="do[delete]" value="delete" class="delete-btn">Delete</button>
                    </li>
                </ul>
            </div>
            <?= $this->paginationControl($paginator, 'Sliding', 'admin/admin/paginator', ['route' => $this->routeName, 'ipp' => $paginator->getItemCountPerPage()]) ?>
            <?= $listTable->getTableHtml() ?>
        </div>
    </form>

</div>