<?php
function createSelectOptions($selectedVal, array $options) {
    $o = '';
    foreach($options as $val=>$label) {
        $selected = '';
        if($selectedVal == $val) {
            $selected = ' selected="selected"';
        }
        $o .= "<option value='{$val}'{$selected}>{$label}</option>";
    }
    return $o;
}

?>

<?php if ($this->pageCount): ?>
    <table class="pagination-control" cellpadding="0" cellspacing="0">
        <tr>
            <td class="left">
                <!-- First page link -->
                <?php if (isset($this->previous)): ?>
                    <a class="first" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->first]]); ?>">
                        <<
                    </a>
                <?php endif; ?>

                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <a class="previous" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]); ?>">
                        <
                    </a>
                <?php endif; ?>

                <input type="number" name="pageItem" value="<?= $this->current ?>"/>
                of <?= $this->last; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <a class="next" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]); ?>">
                        >
                    </a>
                <?php endif; ?>

                <!-- Last page link -->
                <?php if (isset($this->next)): ?>
                    <a class="last" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->last]]); ?>">
                        >>
                    </a>
                <?php endif; ?>
            </td>
            <td class="center">
                Record: <?= $this->totalItemCount ?>
            </td>
            <td class="right">
                <select>
                    <?= createSelectOptions($this->ipp, [25=>'25', 50=>'50', 100=>'100', 250=>'250', 500=>'500', 1000=>'1000']) ?>
                </select>
            </td>
        </tr>
    </table>
<?php endif; ?>