<div class="search-filter">
    <div class="title">Search Filter</div>
    <div class="fields">
        <?php
        $tr = [];
        if (!empty($this->searchList)) {
            foreach ($this->searchList as $key => $item) {
                $field = '';
                if (is_array($item)) {
                    $field = $key;
                } else {
                    $field = $item;
                }
                $tFields = \Libs\Admin\Helper::transformFiled($field, $this->languages);
                foreach ($tFields as $tField) {
                    $td = [];
                    $td[] = '<td>' . $this->formLabel($this->searchForm->get($tField)) . '</td>';
                    $td[] = '<td>' . $this->formElement($this->searchForm->get($tField)) . '</td>';
                    $tr[] = implode('', $td);
                }
            }

            echo $this->form()->openTag($this->searchForm);
            echo '<table cellpadding="0" cellspacing="0"><tr>' . implode('</tr><tr>', $tr) . '</tr></table>';
            echo $this->formElement($this->searchForm->get('submit'));
            echo $this->formElement($this->searchForm->get('clear'));
            echo $this->form()->closeTag();
        }
        ?>
    </div>
</div>
