<div class="search-filter">
    <div class="title">Search Filter</div>

        <?php
        $tr = '';
        if (!empty($this->searchList)) {
            foreach ($this->searchList as $key => $item) {
                $field = '';
                if (is_array($item)) {
                    $field = $key;
                } else {
                    $field = $item;
                }
                $tFields = \Libs\Admin\Helper::transformFiled($field, $this->languages);
                foreach ($tFields as $lng => $tField) {
                    $td = [];

                    $lngClass = '';
                    if($lng != '0') {
                        $lngClass = " class='lng {$lng}'";
                        $td[] = '<td>' . $this->formLabel($this->searchForm->get($tField)) . "<span class='value-lng'>({$lng})</span></td>";
                    } else {
                        $td[] = '<td>' . $this->formLabel($this->searchForm->get($tField)) . '</td>';
                    }
                    $td[] = '<td>' . $this->formElement($this->searchForm->get($tField)) . '</td>';
                    $tr .= "<tr{$lngClass}>" . implode('', $td) . '</tr>';
                }
            }

            echo $this->form()->openTag($this->searchForm);
            echo '<div class="fields">';
            echo '<table cellpadding="0" cellspacing="0"><tr>' . $tr . '</tr></table>';
            echo '</div>';
            echo '<div class="footer">';
            echo $this->formElement($this->searchForm->get('submit'));
            echo $this->formElement($this->searchForm->get('clear'));
            echo '</div>';
            echo $this->form()->closeTag();
        }
        ?>
</div>
